# Generated by Django 3.0.8 on 2020-07-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='poster',
            field=models.URLField(blank=True, default=''),
        ),
    ]
