# Generated by Django 3.0.8 on 2020-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='poster',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
