# Generated by Django 2.2.5 on 2020-07-11 13:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200711_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rights',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'breed': 'collie', 'owner': None}),
        ),
    ]
