# Generated by Django 3.0.8 on 2020-07-11 19:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200711_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='login',
            new_name='second_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='progress',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
